### ISSUE TITLE
Not close connection correctly when use threads?

### ISSUE THREAD

**Issue by yz-gu** [BobBaylor/stream#1]
To begin with, thank you very much for your program. This helps me a lot in utilizing this device and studying how to completing my own program. 
I think there is a tiny issue. In stream.py the code between line 326 and line 331 should not under "else", just adjusting the indent will fix it.
And in case you can see this, I usually encounter an error after connecting for dozens of minutes, saying
`ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`
Do you have any idea what might trigger this disconnection? Thx again.

**Comment by BobBaylor** [comment]
Hi Chris, thanks for the feedback. You are correct: the the time display could be moved outside of the else clause. I will make that change to the code. 
I would like to help with the WinError, too. To help reproduce the problem, please tell me the options you are using. Specifically, --ints, --length, --rate, --silent, --thread, and --vars. Also, what is the time constant setting of the lock-in?  I will be able to test it in about 24 hours when I am in my lab. All the best, 
Bob

**Comment by BobBaylor** [comment]
Oops

**Comment by yz-gu** [comment]
There are nothing special about the options I use, and this error never appears with your program. I suspect this error will be triggered when streaming lasts for too long, or when I don't close the connection correctly, because your program will close the connection after the duration (usually set it to no more than 10 seconds) automatically, while my edited program (which is still in progress) requires me to close it by myself. So maybe sometimes I quit the program without running the close module (cleanup_ifcs()). This also occurs when I use the official software (SR865DataCapture.exe) and I may quit this program before I click stop.
If it helps: I usually set the time constants to 300us or 100us, rate (after decimating) to no more than 20kHz.
